import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "")

LEMON_SQUEEZY_WEBHOOK_SECRET = os.getenv("LEMON_SQUEEZY_WEBHOOK_SECRET", "")
LEMON_SQUEEZY_CHECKOUT_URL_PRO = os.getenv("LEMON_SQUEEZY_CHECKOUT_URL_PRO", "")
LEMON_SQUEEZY_CHECKOUT_URL_SHOP = os.getenv("LEMON_SQUEEZY_CHECKOUT_URL_SHOP", "")
LEMON_SQUEEZY_VARIANT_PRO = os.getenv("LEMON_SQUEEZY_VARIANT_PRO", "")
LEMON_SQUEEZY_VARIANT_SHOP = os.getenv("LEMON_SQUEEZY_VARIANT_SHOP", "")

PORT = int(os.getenv("PORT", "8080"))

FREE_MONTHLY_QUERIES = 3
